# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: P'tite Grenobloise
email: daisyferreira.g@gmail.com
description: My photo book of what I see every day.
baseurl: "/ptitegrenobloise" # the subpath of your site, e.g. /blog
url: "//optitdferreira.github.io" # the base hostname & protocol for your site
twitter_username: daisyf
github_username:  ptitdferreira

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
